a1 = input("Enter your number 1: ")
a2 = input("Enter your number 2: ")
a3 = input("Enter your number 3: ")
a4 = input("Enter your number 4: ")
a5 = input("Enter your number 5: ")
a6 = input("Enter your number 6: ")
a7 = input("Enter your number 7: ")
a8 = input("Enter your number 8: ")

s = set()
s.add(a1)
s.add(a2)
s.add(a3)
s.add(a4)
s.add(a5)
s.add(a6)
s.add(a7)
s.add(a8)
print(s)

a = set()
a.add(20)
a.add(20.0)
a.add("20")
print(a)